# Generated by Django 2.0.7 on 2018-07-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instaclone', '0002_usermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
